---
ID: "28d896e9-8546-4832-836b-899f24be2559"
Parent: "77d82f03-6665-4e9c-9b4d-c52b38479574"
Template: "77d82f03-6665-4e9c-9b4d-c52b38479574"
Path: /sitecore/templates/Feature/Services/Services/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180801T134644Z
    - ID: "47bc55ca-fea1-4d5f-a232-a97de02f120a"
      Hint: Subtitle
      Value: $name Subtitle
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
